version: '3.8'

services:
  employee-service:
    # Build the Docker image using the specified context and Dockerfile
    build:
      context: ./employee-management/
      dockerfile: Dockerfile
    image: employee-service:latest
    container_name: "employee-management"
    # Map ports from host to container
    ports:
      - "8080:8080"
    environment:
      # Define an environment variable for the base URL
      REACT_APP_FRONTEND_URL: 'http://localhost:3000'

  employee-service-ui:
    build:
      context: ./employee-management-ui/
      dockerfile: Dockerfile
    image: employee-service-ui:latest
    container_name: "employee-management-ui"
    # Map ports from host to container
    ports:
      - "3000:3000"
    environment:
      # Define an environment variable for the base URL
      REACT_APP_BACKEND_URL: 'http://localhost:8080/api/employees'
    depends_on:
      - employee-service
